hiss/customauth/urls.py
from customauth import views
from django.urls import path
from django.views.generic.base import RedirectView

app_name = "customauth"
urlpatterns = [
    path(
        "signup/",
        views.AuthRedirectView.as_view(url="/auth/signup", permanent=False),
        name="signup",
    ),
    path(
        "login/",
        views.AuthRedirectView.as_view(url="/auth/login", permanent=False),
        name="login",
    ),
    path(
        "logout/",
        views.RemoteLogoutView.as_view(url="/auth/logout", permanent=False),
        name="logout",
    ),
]

hiss/hiss/urls.py
from django import http
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView


def healthcheck(request):
    return http.HttpResponse("")


urlpatterns = [
    url(settings.BASE_PATHNAME + "admin/login", RedirectView.as_view(url="/auth/login?r=/apply/admin/application/application")),
    path(settings.BASE_PATHNAME + "admin/", admin.site.urls),
    path(settings.BASE_PATHNAME + "accounts/", include("customauth.urls")),
    path(
        settings.BASE_PATHNAME + "application/",
        include("application.urls", namespace="application"),
    ),
    path(settings.BASE_PATHNAME + "healthy/", healthcheck),
    url(settings.BASE_PATHNAME_REGEX, RedirectView.as_view(pattern_name="status"),),
    path(settings.BASE_PATHNAME + "status/", include("status.urls")),
    path(settings.BASE_PATHNAME + "team/", include("team.urls")),
    path(settings.BASE_PATHNAME + "api/volunteer/", include("volunteer.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hiss/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta lang="en" />
    <title>{{event_name}}</title>
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}" />
    {% block additional_CSS %} {% endblock %}
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
      crossorigin="anonymous"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>

  <body>
    {% block body %} {% endblock %}

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script src="{%  static 'main.js' %}"></script>
  </body>
</html>

hiss/templates/dashboard_base.html
{% extends 'base.html' %} {% load static %} {% block body %}
<section class="dashboard">
  <nav class="navbar navbar-expand-md navbar-light nav-bg" role="navigation">
    <span class="navbar-span">
      <button
        class="navbar-toggler hidden-sm-up float-xs-right"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <img
        src="https://tamudatathon.com/static/img/logos/main-22.webp"
        class="navbar-logo d-none d-md-block"
      />
    </span>
    <div
      class="collapse navbar-collapse"
      id="navbarSupportedContent"
    >
      <div class="navbar-nav justify-content-center w-100">
        <a class="nav-item" href="/">Home</a>
        <a class="nav-item" href="/events">Events</a>
        <a class="nav-item" href="/schedule">Schedule</a>
        <a class="nav-item" href="/challenges">Challenges</a>
        <a class="nav-item" href="/apply">Apply</a>
      </div>
      <a class="nav-item logout-link" href="{% url 'customauth:logout' %}">Logout</a>
    </div>
  </nav>

  <div class="container">
    <div class="row justify-content-center">
      <div
        class="col justify-content-center col-xl-10 col-md-12 pt-4 inner-container"
      >
        <div>
          {% block content %} {% endblock %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}