hiss/application/urls.py
from django.urls import path

from application import views

app_name = "application"
urlpatterns = [
    path("", views.CreateApplicationView.as_view(), name="create"),
    path("<uuid:pk>", views.UpdateApplicationView.as_view(), name="update"),
    path("<uuid:pk>/confirm", views.ConfirmApplicationView.as_view(), name="confirm"),
    path("<uuid:pk>/decline", views.DeclineApplicationView.as_view(), name="decline"),
    path("all", views.GetApplicationsCsvView.as_view(), name="get_all_applications"),
    path("all/json", views.GetApplicationsJsonView.as_view(), name="get_all_applications_json"),
]

hiss/hiss/urls.py
from django import http
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView


def healthcheck(request):
    return http.HttpResponse("")


urlpatterns = [
    url(settings.BASE_PATHNAME + "admin/login", RedirectView.as_view(url="/auth/login?r=/apply/admin/application/application")),
    path(settings.BASE_PATHNAME + "admin/", admin.site.urls),
    path(settings.BASE_PATHNAME + "accounts/", include("customauth.urls")),
    path(
        settings.BASE_PATHNAME + "application/",
        include("application.urls", namespace="application"),
    ),
    path(settings.BASE_PATHNAME + "healthy/", healthcheck),
    url(settings.BASE_PATHNAME_REGEX, RedirectView.as_view(pattern_name="status"),),
    path(settings.BASE_PATHNAME + "status/", include("status.urls")),
    path(settings.BASE_PATHNAME + "team/", include("team.urls")),
    path(settings.BASE_PATHNAME + "api/volunteer/", include("volunteer.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hiss/status/urls.py
from django.urls import path

from status import views

urlpatterns = [path("", views.StatusView.as_view(), name="status")]

hiss/team/urls.py
from django.urls import path

from team import views

urlpatterns = [
    path("", views.CreateTeamView.as_view(), name="create"),
    path("join", views.JoinTeamView.as_view(), name="join"),
    path("leave", views.LeaveTeamView.as_view(), name="leave"),
    path("<uuid:pk>", views.DetailTeamView.as_view(), name="detail"),
]
app_name = "team"

hiss/status/views.py
from django.contrib.auth import mixins
from django.views import generic

from application import models as application_models
from application.models import Wave, Application
from user.models import User


class StatusView(mixins.LoginRequiredMixin, generic.TemplateView):
    template_name = "status/status.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user: User = self.request.user

        active_wave = Wave.objects.active_wave()
        if not active_wave and not user.application_set.exists():
            next_wave = Wave.objects.next_wave()
            if not next_wave:
                context["NO_MORE_WAVES"] = True
            else:
                context["WAIT_UNTIL_NEXT_WAVE"] = True
                context["next_wave_start"] = next_wave.start
        else:
            if active_wave:
                context["active_wave_end"] = active_wave.end
            if not user.application_set.exists():
                context["NOT_APPLIED"] = True
                return context
            app: Application = user.application_set.first()
            app_status = app.status
            if app_status == application_models.STATUS_PENDING:
                context["PENDING"] = True
                context["application"] = app
            elif app_status == application_models.STATUS_REJECTED:
                context["REJECTED"] = True
            elif app_status == application_models.STATUS_ADMITTED or app_status == application_models.STATUS_ADMITTED_VIRTUAL:
                context["NEEDS_TO_CONFIRM"] = True
                context["application"] = app
                context["confirmation_deadline"] = app.confirmation_deadline
            elif app_status == application_models.STATUS_CONFIRMED:
                context["CONFIRMED"] = True
            elif app_status == application_models.STATUS_DECLINED:
                context["DECLINED"] = True
            elif app_status == application_models.STATUS_CHECKED_IN:
                context["CHECKED_IN"] = True
            elif app_status == application_models.STATUS_EXPIRED:
                context["EXPIRED"] = True
        return context

hiss/templates/status/status.html
{% extends 'dashboard_base.html' %} {% load static %} {% block content %}
    {% load tz %}
    {% get_current_timezone as TIME_ZONE %}
    <div class="status-box">
        <header>
            {% if CONFIRMED or NEEDS_TO_CONFIRM or DECLINED %}
                <ol class="timeline-24">
            {% else %}
                <ol class="timeline">
            {% endif %}

            <li>
                <p class="diplome">Submitted</p>
                {% if CONFIRMED or REJECTED or PENDING or NEEDS_TO_CONFIRM or DECLINED %}
                    <img src="{% static 'tick.svg' %}">
                {% else %}
                    <span class="point"></span>
                {% endif %}
            </li>
            <li>
                <p class="diplome">In Review</p>
                {% if CONFIRMED or REJECTED or NEEDS_TO_CONFIRM or WAIT_UNTIL_NEXT_WAVE or DECLINED %}
                    <img src="{% static 'tick.svg' %}">
                {% else %}
                    <span class="point"></span>
                {% endif %}
            </li>
            <li>
                <p class="diplome">Decisions Released</p>
                {% if CONFIRMED or REJECTED or NEEDS_TO_CONFIRM or DECLINED %}
                    <img src="{% static 'tick.svg' %}">
                {% else %}
                    <span class="point"></span>
                {% endif %}
            </li>
            </ol>
        </header>

        <div class="pt-4 text-center submit-pg">
            <br>
            {% if NOT_APPLIED %}
                <p> Your application is </p>
                <div class="app-status">INCOMPLETE</div>

                <p class="status-subtitle pt-2" style="margin-bottom: 0;">
                    Submit your application before {{ active_wave_end }} {{ TIME_ZONE }} to be considered.
                </p>

                <div class="row login-alt-options pt-4">
                    <div class="col-sm-12 col-lg-12 text-center">
                        <br>
                        <a href="{% url 'application:create' %}" class="btn btn-login">Complete Application</a>
                    </div>
                </div>

            {% elif PENDING %}
                <p> Your application has been </p>
                <div class="app-status">SUBMITTED</div>

                <p class="status-subtitle pt-2">
                    Thanks for applying! We'll email you as soon as decisions are released.
                </p>
                <div class="row login-alt-options">
                    <div class="col-sm-12 col-lg-12 text-center">

                        <br>
                        <a href="{{ application.get_absolute_url }}" class="btn btn-login">
                            {% if active_wave_end %}
                                Edit Application
                            {% else %}
                                View Application
                            {% endif %}
                        </a>

                    </div>
                </div>

            {% elif NEEDS_TO_CONFIRM and not DECLINED %}
                <p> Congrats, you have been </p>
                {% if application.status == "V" %}
                <div class="app-status">ACCEPTED FOR VIRTUAL</div>
                <p class="status-subtitle pt-2">
                    You have been accepted to attend TAMU Datathon 2022 virtually!
                </p>
                {% else %}
                <div class="app-status">ACCEPTED FOR IN-PERSON</div>
                <p class="status-subtitle pt-2">
                    You have been accepted to attend TAMU Datathon 2022 in person! Check the website for location details and transportation information.
                </p>
                {% endif %}

                <p class="status-subtitle pt-2">
                    {% localtime off %}
                        Please RSVP below by {{ confirmation_deadline }} {{ TIME_ZONE }} or you risk losing your spot.
                    {% endlocaltime %}
                </p>
                <div class="row login-alt-options">
                    <div class="col-sm-12 col-lg-12 text-center">
                        <br>
                        <form method="POST" action="{% url 'application:confirm' pk=application.pk %}" class="rsvp-response-btn">
                            {% csrf_token %}

                            <input class="btn btn-login" type="submit" value="I'll be there!">
                        </form>
                        <form method="POST" action="{% url 'application:decline' pk=application.pk %}" class="rsvp-response-btn">
                            {% csrf_token %}

                            <input class="btn btn-login secondary" type="submit" value="I can't make it">
                        </form>
                    </div>
                </div>

            {% elif CONFIRMED %}
                <p>Your application has been</p>
                <div class="app-status">ACCEPTED</div>

                <p class="status-subtitle pt-2">
                    Congratulations! Prepare for the event by visiting <a href="https://tamudatathon.com">our homepage</a>. We should also be sending out an email with important event information as we get closer to the event. See you soon!
                </p>

                <p>
                    Have additional questions? Email us at <a href="mailto:connect@tamudatathon.com">connect@tamudatathon.com</a>
                </p>

            {% elif REJECTED %}
                <p> Your application has been </p>
                <div class="app-status">WAITLISTED</div>

                <p class="status-subtitle pt-2">
                    Unfortunately, you have not been admitted into the event.
                </p>

                <div class="row login-alt-options pt-4">
                    <div class="col-sm-12 col-lg-12 text-center">
                        <br>
                        <a href="{{ application.get_absolute_url }}" class="btn btn-login">View Application</a>
                    </div>
                    {% elif DECLINED %}
                    <div class="app-status">Not Attending</div>

                    <p class="pt-2">We're sorry to hear you can't make it! Thanks for telling us!</p>

                    {% elif NO_MORE_WAVES %}
                    <p>Sorry, we are currently not accepting applications.</p>
                </div>
            {% elif EXPIRED %}
                <p>Your confirmation deadline has</p>
                <div class="app-status">EXPIRED</div>
                <p class="status-subtitle pt-2">
                    You did not confirm your attendance by the deadline provided, so we have given your spot to other
                    applicants.
                </p>
            {% endif %}
        </div>
    </div>
{% endblock %}