hiss/hiss/urls.py
from django import http
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView


def healthcheck(request):
    return http.HttpResponse("")


urlpatterns = [
    url(settings.BASE_PATHNAME + "admin/login", RedirectView.as_view(url="/auth/login?r=/apply/admin/application/application")),
    path(settings.BASE_PATHNAME + "admin/", admin.site.urls),
    path(settings.BASE_PATHNAME + "accounts/", include("customauth.urls")),
    path(
        settings.BASE_PATHNAME + "application/",
        include("application.urls", namespace="application"),
    ),
    path(settings.BASE_PATHNAME + "healthy/", healthcheck),
    url(settings.BASE_PATHNAME_REGEX, RedirectView.as_view(pattern_name="status"),),
    path(settings.BASE_PATHNAME + "status/", include("status.urls")),
    path(settings.BASE_PATHNAME + "team/", include("team.urls")),
    path(settings.BASE_PATHNAME + "api/volunteer/", include("volunteer.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hiss/team/urls.py
from django.urls import path

from team import views

urlpatterns = [
    path("", views.CreateTeamView.as_view(), name="create"),
    path("join", views.JoinTeamView.as_view(), name="join"),
    path("leave", views.LeaveTeamView.as_view(), name="leave"),
    path("<uuid:pk>", views.DetailTeamView.as_view(), name="detail"),
]
app_name = "team"

hiss/team/models.py
import uuid

from django.db import models
from django.urls import reverse_lazy


class Team(models.Model):
    """A representation of a hackathon team that can be used for team-based admission."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    admitted = models.NullBooleanField(blank=True)

    def get_absolute_url(self):
        return reverse_lazy("team:detail", args=[self.id])

hiss/team/forms.py
from django import forms

from team.models import Team


class CreateTeamForm(forms.ModelForm):
    """
    Creates a new Team. See superclass documentation for further details.
    """

    class Meta:
        model = Team
        widgets = {"name": forms.TextInput(attrs={"placeholder": "Team Name"})}
        fields = ["name"]


class JoinTeamForm(forms.Form):
    """
    A generic Django form. The "id" field is used to look up the corresponding Team.
    """

    id = forms.UUIDField(label="Use the Team ID to join an existing team")

hiss/team/views.py
from typing import Optional

from django.conf import settings
from django.http import HttpRequest
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

from shared import mixins as shared_mixins

from team.forms import CreateTeamForm, JoinTeamForm
from team.models import Team
from user.models import User
from application.models import Application


class CreateTeamView(shared_mixins.UserHasNoTeamMixin, generic.CreateView):
    """
    If the user has applied, creates a Team and adds the User to it.
    """

    form_class = CreateTeamForm
    template_name = "team/team_form.html"

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            return redirect(
                f"{reverse_lazy('customauth:login')}?next={reverse_lazy('team:create')}"
            )
        return redirect(reverse_lazy("status"))

    def form_valid(self, form: CreateTeamForm):
        team: Team = form.save()
        user: User = self.request.user
        if self.request.user.team is not None:
            form.add_error(
                None,
                "You cannot create a new team while currently on a team. Please leave your current team "
                "and try again.",
            )
            return self.form_invalid(form)
        user.team = team
        user.save()
        return redirect(team.get_absolute_url())


class JoinTeamView(shared_mixins.UserHasNoTeamMixin, generic.FormView):
    """
    Adds the user to a team (if the team isn't already at capacity).
    """

    form_class = JoinTeamForm
    template_name = "team/join_form.html"

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            return redirect(
                f"{reverse_lazy('customauth:login')}?next={reverse_lazy('team:join')}"
            )
        return redirect(reverse_lazy("status"))

    def get_success_url(self):
        return self.request.user.team.get_absolute_url()

    def form_valid(self, form: JoinTeamForm):
        team: Optional[Team] = Team.objects.filter(id=form.cleaned_data["id"]).first()
        if not team:
            form.add_error(None, "No such team exists.")
            return self.form_invalid(form)
        if team.members.count() == settings.MAX_MEMBERS_PER_TEAM:
            form.add_error(None, "This team is already at capacity.")
            return self.form_invalid(form)
        if self.request.user.team is not None:
            form.add_error(
                None,
                "You cannot be on more than one team at a time. Please leave your existing team and try "
                "again.",
            )
            return self.form_invalid(form)
        self.request.user.team = team
        self.request.user.save()
        return super().form_valid(form)


class DetailTeamView(shared_mixins.UserHasTeamMixin, generic.DetailView):
    """
    Renders a Team if the User is a member.
    """

    model = Team
    template_name = "team/team_detail.html"

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            team_pk = self.kwargs["pk"]
            return redirect(
                f"{reverse_lazy('customauth:login')}?next={reverse_lazy('team:detail', args=[team_pk])}"
            )
        if not Application.objects.filter(user=self.request.user.pk):
            return redirect(reverse_lazy("status"))
        if self.request.user.team is None:
            return redirect(reverse_lazy("team:join"))
        return redirect(reverse_lazy("status"))

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        team: Team = self.get_object()
        member_applications = [
            member.application_set.first() for member in team.members.all()
        ]
        context_data["member_applications"] = member_applications
        return context_data

    def get(self, request, *args, **kwargs):
        team: Team = self.get_object()
        if self.request.user.team != team:
            return redirect(
                reverse_lazy("team:detail", args=[self.request.user.team.pk])
            )
        return super().get(request, *args, **kwargs)


class LeaveTeamView(shared_mixins.LoginRequiredAndAppliedMixin, generic.base.View):
    """
    Removes a User from a Team. If the Team no longer has members, deletes the Team.
    """

    def post(self, request: HttpRequest, *_args, **_kwargs):
        team: Team = request.user.team
        request.user.team = None
        request.user.save()

        team.refresh_from_db()
        if team.members.count() == 0:
            team.delete()
        return redirect(reverse_lazy("status"))

hiss/templates/team/join_form.html
{% extends 'dashboard_base.html' %} {% block content %}{% load static %}

<div class="team-form mt-4">
        <h3 class="text-center">Join an existing team</h3>
        
        <div class="row pt-5">
            <div class="col-12">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                   
                    <button type="submit" class="btn secondary btn-block btn-lg btn-login w-100">
                        Join
                    </button>    
                </form>
            </div>
            <div class="col-12 text-center mt-5">
                Don't have a team ID? <a href="{% url 'team:create'  %}">Create a New Team</a>
            </div>
        </div>
    </div>

{% endblock %}

hiss/templates/team/team_detail.html
{% extends 'dashboard_base.html' %} {% block content %}{% load static %}

<div class="team-detail">
    <h3 class="mb-5">{{ settings.EVENT_NAME }} 2020 Team</h3>

    <div class="row">
        <div class="col-12 col-md-6">
            <h4>Team Name</h4>
            <h5>{{ object.name }}</h5>

            <br>

            <h4>Team ID</h4>
            <h5>{{ user.team.id }}</h5>
            <p class="note">(Use this code to invite others to join your team)</p>
            <br>

        </div>

        <div class="col-12 col-md-6">
            <h4>Team Members</h4>
            {% for application in member_applications %}
                <h5>{{ application.first_name }} {{ application.last_name }}</h5>
            {% endfor %}
        </div>
    </div>
    
    <form method="POST" action="{% url 'team:leave' %}">
        {% csrf_token %}
        <input type="submit" value="LEAVE TEAM" class="btn btn-login btn-block btn-width">
    </form>

</div>

{% endblock %}

hiss/templates/team/team_form.html
{% extends 'dashboard_base.html' %} {% block content %}{% load static %}

    <div class="team-form  mt-4">
        <h3 class="text-center">Create a new team</h3>
        
        <div class="row pt-5">
            <div class="col-12 create">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                   
                    <button type="submit" class="btn btn-block btn-lg btn-login w-100">
                        Create
                    </button>    
                </form>
            </div>
            <div class="col-12 text-center mt-5">
                Already have a team ID? <a href="{% url 'team:join'  %}">Join Team</a>
            </div>
        </div>
    </div>

{% endblock %}